### ISSUE TITLE
EKS failed because EBS does not support `ReadWriteMany` mode

### ISSUE THREAD

**Issue by Imccccc** [BorisPolonsky/dify-helm#8]
I am not sure it is a good idea that api and worker share the same path.

**Comment by BorisPolonsky** [comment]
> I am not sure it is a good idea that api and worker share the same path.

It's implemented this way according to the [api](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml#L153-L155) and [worker](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml#L153-L155) section in official `docker-compose.yaml`. We haven't gone through code detail in `defy` so you may wish to submit [issues](https://github.com/langgenius/dify/issues) in official repo to opt out possible path collision in the application in case path are shared.

As for the problem stated in the title (EKS failed because EBS does not support ReadWriteMany mode), could you elaborate and   clarify the steps to replicate your issue. From our understanding there are multiple components that need `PVC` deployed. If it's related to `redis`, `postgresql`, these dependencies are inherit from charts published by [bitnami](https://github.com/bitnami/charts). You can enable external `redis` and `postgresql` to solve that. As for the storage for `api` and `worker`, you may use external S3 as an option instead of using `PVC`, or any `PVC` that supports `ReadWriteMany`. If you could confirm modes other than `ReadWriterMany` that are practical in this case, please let us know.

**Comment by Imccccc** [comment]
Cause EKS default storage class gp2 using EBS as backend, and EBD only mounted on one node.
I changed the storage class backed by EFS, the problem solved. 
EFS driver reference is here: [efs-csi](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html#efs-install-driver
)
